### ISSUE TITLE
error occured when start planner

### ISSUE THREAD

**Issue by qycqycqyc** [unr-arl/mbplanner_ros#10]
Input pointcloud queue getting too long! Dropping some pointclouds. Either unable to look up transform timestamps or the processing is taking too long.

**Comment by MihirDharmadhikari** [comment]
Hello, 

Sorry for the delay in response. The above error is a known issue in voxblox that occurs when it tries to integrate a large pointcloud. However, if the map is building properly then this error can be safely ignored.

Best,
Mihir
