### ISSUE TITLE
How to use RGB-D camera?

### ISSUE THREAD

**Issue by engcang** [unr-arl/mbplanner_ros#4]
Hi.  @MihirDharmadhikari ,
I really appreciate sharing this great repo.

I tried to use RGB-D camera by changing all of

+ exploration/mbplanner_ros/global_planner/config/global_planner_config.yaml
+ exploration/mbplanner_ros/mbplanner/config/mbplanner_config.yaml
+ exploration/mbplanner_ros/mbplanner/config/octomap_sim_config.yaml
+ exploration/mbplanner_ros/mbplanner/config/planner_control_interface_sim_config.yaml
+ exploration/mbplanner_ros/mbplanner/mbplanner.launch

especially, `global_planner_config.yaml` and `mbplanner_config.yaml`.

I changed the `SensorParams` as
    type:           kCamera
    max_range:      15.0
    center_offset:  [0.0, 0.0, 0.0]
    rotations:      [0.0, 0.0, 0.0]
    fov:            [rad(pi/2), rad(pi/3)]
    resolution:     [rad(5.0*pi/180), rad(3.0*pi/180)]

But right after I changed the sensorparams, I can get only

[ WARN] [1607363547.506713317, 30.048000000]: No positive gain for any vertex
[ WARN] [1607363547.506726017, 30.048000000]: Zero gain
[ WARN] [1607363547.506776290, 30.048000000]: Planner service failed

Zero gain continuously.

Did I set any configuration wrong to use RGB-D Camera?

thank you in advance.

**Comment by MihirDharmadhikari** [comment]
Hello,

I checked the same thing and I found a bug in the kCamera model. I have fixed the issue in this [pull request](https://github.com/unr-arl/mbplanner_ros/pull/5l). This has now been merged into the master.
Thank you very much for pointing this out.
Please let me know if you face any other problems.

**Comment by engcang** [comment]
Cool! Thanks a lot for your fast reply and fix!! It works great now :) :100:
